pages:
  image: node:14.9.0
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build
    - mv public public_files
    - mv dist public
  artifacts:
    expire_in: 1 week
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - react
