image: node:17.1.0-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  cache:
    paths:
      - node_modules

lint:
  stage: test
  allow_failure: true
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm lint & pnpm lint-junit
  artifacts:
    reports:
      junit: eslint.xml
  cache:
    paths:
      - node_modules
  needs:
    - build

check:
  stage: test
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm check
  cache:
    paths:
      - node_modules
  needs:
    - build

pages:
  image: alpine
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: 'false'
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - mv dist public
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - svelte
